# Boolean array indexing

This advanced indexing occurs when obj is an array object of Boolean type, such as may be returned from comparison operators. A single boolean index array is practically identical to x[obj.nonzero()] where, as described above, obj.nonzero() returns a tuple (of length obj.ndim) of integer index arrays showing the True elements of obj. However, it is faster when obj.shape == x.shape.

If obj.ndim == x.ndim, x[obj] returns a 1-dimensional array filled with the elements of x corresponding to the True values of obj. The search order will be row-major, C-style. An index error will be raised if the shape of obj does not match the corresponding dimensions of x, regardless of whether those values are True or False.

A common use case for this is filtering for desired element values. For example, one may wish to select all entries from an array which are not numpy.nan:

In [36]:
import numpy as np
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [2]:
np.isnan(x)

array([[False, False],
       [ True, False],
       [ True,  True]])

In [3]:
~np.isnan(x)

array([[ True,  True],
       [False,  True],
       [False, False]])

In [37]:
x[~np.isnan(x)]

array([1., 2., 3.])

Or wish to add a constant to all negative elements:

In [5]:
x = np.array([1., -1., -2., 3])
x

array([ 1., -1., -2.,  3.])

In [6]:
x[x < 0]

array([-1., -2.])

In [7]:
x[x < 0] += 20

In [8]:
x

array([ 1., 19., 18.,  3.])

In general if an index includes a Boolean array, the result will be identical to inserting obj.nonzero() into the same position and using the integer array indexing mechanism described above. x[ind_1, boolean_array, ind_2] is equivalent to x[(ind_1,) + boolean_array.nonzero() + (ind_2,)].

If there is only one Boolean array and no integer indexing array present, this is straightforward. Care must only be taken to make sure that the boolean index has exactly as many dimensions as it is supposed to work with.

In general, when the boolean array has fewer dimensions than the array being indexed, this is equivalent to x[b, ...], which means x is indexed by b followed by as many : as are needed to fill out the rank of x. Thus the shape of the result is one dimension containing the number of True elements of the boolean array, followed by the remaining dimensions of the array being indexed:

In [9]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b[:, 5]

array([False, False, False,  True,  True])

In [10]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [11]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

## Problem 1

From an array, select all rows which sum up to less or equal two:

In [12]:
x = np.array([[0, 1], [1, 1], [2, 2]])
x

array([[0, 1],
       [1, 1],
       [2, 2]])

Sample Solution 

In [38]:
rowsum = x.sum(-1)
rowsum

array([ 3., nan, nan])

In [39]:
rowsum <= 2

array([False, False, False])

In [15]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

below works?  why?

In [16]:
x[rowsum <= 2]

array([[0, 1],
       [1, 1]])

## Problem 2

In [42]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

which is rame as 

In [18]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Use boolean indexing to select all rows adding up to an even number. At the same time columns 0 and 2 should be selected with an advanced integer index. Using the ix_ function this can be done with:

In [20]:
np.ix_?

Signature:       np.ix_(*args)
Call signature:  np.ix_(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function ix_ at 0x000002622C481BD0>
File:            c:\users\hongbo\appdata\local\programs\python\python310\lib\site-packages\numpy\lib\_index_tricks_impl.py
Docstring:      
Construct an open mesh from multiple sequences.

This function takes N 1-D sequences and returns N outputs with N
dimensions each, such that the shape is 1 in all but one dimension
and the dimension with the non-unit shape value cycles through all
N dimensions.

Using `ix_` one can quickly construct index arrays that will index
the cross product. ``a[np.ix_([1,3],[2,5])]`` returns the array
``[[a[1,2] a[1,5]], [a[3,2] a[3,5]]]``.

Parameters
----------
args : 1-D sequences
    Each sequence should be of integer or boolean type.
    Boolean sequences will be interpreted as boolean masks for the
    corresponding dimension (equivalent to passing in
    ``np.nonzero(boolean_sequence)``)

In [21]:
np.ix_([0, 1,3], [2, 4])

(array([[0],
        [1],
        [3]]),
 array([[2, 4]]))

In [43]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
rows = (x.sum(-1) % 2) == 0
rows

array([False,  True, False,  True])

In [23]:
columns = [0, 2]

In [45]:
np.ix_(rows, columns)

(array([[1],
        [3]]),
 array([[0, 2]]))

In [25]:
np.ix_(rows, columns)

(array([[1],
        [3]]),
 array([[0, 2]]))

In [26]:
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

Without the np.ix_ call, only the diagonal elements would be selected.

In [27]:
x[rows,columns]

array([ 3, 11])

In [53]:
rows = np.array([[1,3],[0,4],[3,6]])

Or without np.ix_ (compare the integer array examples):

In [54]:
rows = rows.nonzero()[0]
rows

array([0, 0, 1, 2, 2])

In [56]:
rows[:, np.newaxis]

array([[0],
       [0],
       [1],
       [2],
       [2]])

In [58]:
columns

[0, 2]

In [60]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
x[rows[:, np.newaxis], columns]

array([[0, 2],
       [0, 2],
       [3, 5],
       [6, 8],
       [6, 8]])

## Problem 3

Use a 2-D boolean array of shape (2, 3) with four True elements to select rows from a 3-D array of shape (2, 3, 5) results in a 2-D result of shape (4, 5):

In [61]:
x = np.arange(30).reshape(2, 3, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [62]:
b = np.array([[True, True, False], [False, True, True]])
b

array([[ True,  True, False],
       [False,  True,  True]])

In [ ]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])